# This file can be used to create a fresh conda env:
# `conda env create -f environmental.yml -n ipyrad2`
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.8
  - loguru
  - numba
  - numpy
  - pandas
  - h5py
  - samtools
  - bedtools
  - bcftools
  - fastp
  - bwa-mem2
  # - toytree >=3.0.1