#!/usr/bin/env python

"""TreeSlider command line."""

from __future__ import annotations

import argparse
from pathlib import Path

from .common import RAW_HELP_FORMATTER


EPILOG = r"""
Examples
--------
$ ipyrad2 treeslider -d assembly.hdf5 --print-scaffold-table
$ ipyrad2 treeslider -d assembly.hdf5 -o OUT/ -n loci
$ ipyrad2 treeslider -d assembly.hdf5 -o OUT/ -n loci --scaffolds chr1 chr2
$ ipyrad2 treeslider -d assembly.hdf5 -o OUT/ -n windows --window-size 100000 --slide-size 50000
$ ipyrad2 treeslider -d assembly.hdf5 -o OUT/ -n windows --window-size 100000 --scaffolds chr*
$ ipyrad2 treeslider -d assembly.hdf5 -o OUT/ -n windows -i POPS.txt -g MINMAP.txt --bs-trees 200
"""


def _int_or_auto(value: str) -> int | str:
    """Parse one positive integer or the literal ``auto``."""
    if value == "auto":
        return value
    parsed = int(value)
    if parsed < 1:
        raise argparse.ArgumentTypeError("value must be >= 1 or 'auto'")
    return parsed


def _setup_treeslider_subparser(
    subparsers: argparse._SubParsersAction,
    header: str = None,
) -> None:
    """Add `ipyrad2 treeslider` subcommand parser."""
    tool = subparsers.add_parser(
        "treeslider",
        description=header,
        help="Extract filtered sequence windows and infer one tree per window with raxml-ng.",
        epilog=EPILOG,
        formatter_class=RAW_HELP_FORMATTER,
        add_help=False,
    )

    core = tool.add_argument_group("Core inputs")
    core.add_argument(
        "-d", "--data", metavar="Path", type=Path, required=True,
        help="Path to an assembly HDF5 file generated by ipyrad2.",
    )
    core.add_argument(
        "-n", "--name", metavar="str", type=str, default="treeslider",
        help="Prefix name for output files. [default=treeslider]",
    )
    core.add_argument(
        "-o", "--out", metavar="Path", type=Path, default="output-treeslider",
        help="Directory to write treeslider outputs. [default=output-treeslider]",
    )

    windowing = tool.add_argument_group("Window planning")
    windowing.add_argument(
        "--window-size", metavar="int", type=int,
        help="Genomic sliding-window size in bp. If omitted, treeslider runs in one-tree-per-locus mode.",
    )
    windowing.add_argument(
        "--slide-size", metavar="int", type=int,
        help="Genomic sliding-window step size in bp. Defaults to the value of --window-size.",
    )
    windowing.add_argument(
        "--scaffolds", metavar="str", type=str, nargs="*",
        help="Optional scaffold names or shell-style wildcard patterns. If omitted, all scaffolds are selected.",
    )
    windowing.add_argument(
        "-P", "--print-scaffold-table", action="store_true",
        help="Print the scaffold table to stdout and exit.",
    )

    filtering = tool.add_argument_group("Filtering and samples")
    filtering.add_argument(
        "-m", "--min-sample-coverage", metavar="int", type=int, default=4,
        help="Minimum number of samples that must have data at a site. [default=4]",
    )
    filtering.add_argument(
        "--min-sample-alignment-length", metavar="int", type=int, default=1,
        help="Minimum non-missing columns per sample after site filtering, or that sample is excluded. [default=1]",
    )
    filtering.add_argument(
        "--min-alignment-length", metavar="int", type=int, default=1,
        help="Minimum columns remaining after filtering, or the window is excluded. [default=1]",
    )
    filtering.add_argument(
        "-e", "--exclude", metavar="str", type=str, nargs="*",
        help="Exclude one or more samples by name. This takes precedence over IMAP membership and `-R`.",
    )
    filtering.add_argument(
        "-R", "--include-reference", action="store_true",
        help="Include `assembly_reference_sequence`. By default it is excluded unless IMAP already contains it.",
    )
    filtering.add_argument(
        "-i", "--imap", metavar="Path", type=Path,
        help="Sample-to-population mapping file with `sample<TAB>population` or `glob<TAB>population` on each line.",
    )
    filtering.add_argument(
        "-g", "--minmap", metavar="Path", type=Path,
        help="Population-to-minimum-coverage mapping file with `population<TAB>min` on each line. Overrides `-m`.",
    )

    inference = tool.add_argument_group("Tree inference")
    inference.add_argument(
        "--threads", metavar="int|auto", type=_int_or_auto, default="auto",
        help="Threads to pass to each raxml-ng job, or `auto`. [default=auto]",
    )
    inference.add_argument(
        "--workers", metavar="int|auto", type=_int_or_auto, default="auto",
        help="Number of raxml-ng jobs to run in parallel, or `auto`. [default=auto]",
    )
    inference.add_argument(
        "--bs-trees", metavar="int", type=int, default=0,
        help="Number of bootstrap trees to infer per window. Use 0 to disable bootstrapping. [default=0]",
    )
    inference.add_argument(
        "--model", metavar="str", type=str, default="GTR+G",
        help="Substitution model to pass to raxml-ng. [default=GTR+G]",
    )
    inference.add_argument(
        "--raxml-ng-binary", metavar="Path", type=Path,
        help="Optional explicit path to the raxml-ng executable.",
    )
    inference.add_argument(
        "--seed", metavar="int", type=int,
        help="Random seed for raxml-ng and any deterministic restart ordering.",
    )
    inference.add_argument(
        "--redo", action="store_true",
        help="Retry windows that previously failed tree inference while preserving completed windows.",
    )
    inference.add_argument(
        "-f", "--force", action="store_true",
        help="Restart the treeslider run from scratch and overwrite any existing outputs.",
    )

    logging = tool.add_argument_group("Logging")
    logging.add_argument(
        "-l", "--log-level", metavar="str", type=str, default="INFO",
        help="Log level (TRACE, DEBUG, INFO, WARNING, ERROR) [default=INFO]",
    )
    logging.add_argument(
        "-h", "--help", action="help",
        help="Show this help message and exit.",
    )
