#!/usr/bin/env python

"""SNPs extracter command line."""

import argparse
from pathlib import Path

from .common import RAW_HELP_FORMATTER


EPILOG = r"""
Examples
--------
$ ipyrad2 snpex -d assembly.hdf5 -o OUT/
$ ipyrad2 snpex -d assembly.hdf5 -o OUT/ -n SNPSET --seed 123 --phylip
$ ipyrad2 snpex -d assembly.hdf5 -o OUT/ --no-subsample --plink --impute-method sample
$ ipyrad2 snpex -d assembly.hdf5 -o OUT/ -i POPs.txt -g MINs.txt
"""


def _setup_snpex_subparser(
    subparsers: argparse._SubParsersAction,
    header: str = None,
) -> None:
    """Add `ipyrad2 snpex` subcommand parser."""
    tool = subparsers.add_parser(
        "snpex",
        description=header,
        help="Extract filtered SNP matrices from an HDF5 database.",
        epilog=EPILOG,
        formatter_class=RAW_HELP_FORMATTER,
        add_help=False,
    )

    core = tool.add_argument_group("Core inputs")
    core.add_argument(
        "-d", "--data", metavar="Path", type=Path, required=True,
        help="Path to an SNP-capable HDF5 file generated by ipyrad2 or `ipyrad2 vcf2hdf5`.",
    )
    core.add_argument(
        "-n", "--name", metavar="str", type=str, default="snps",
        help="Prefix name for output files. [default=snps]",
    )
    core.add_argument(
        "-o", "--out", metavar="Path", type=Path, default="output-snpex",
        help="Directory to write SNP outputs and stats. [default=output-snpex]",
    )

    filtering = tool.add_argument_group("Filtering and samples")
    filtering.add_argument(
        "-m", "--min-sample-coverage", metavar="int", type=int, default=4,
        help="Minimum number of samples that must have data at a SNP. [default=4]",
    )
    filtering.add_argument(
        "-r", "--max-sample-missing", metavar="float", type=float, default=1.0,
        help="Maximum missing-data frequency allowed in a sample. [default=1.0]",
    )
    filtering.add_argument(
        "-a", "--min-minor-allele-frequency", metavar="float", type=float, default=0.0,
        help="Minimum minor allele frequency required to retain a SNP. [default=0.0]",
    )
    filtering.add_argument(
        "-e", "--exclude", metavar="str", type=str, nargs="*",
        help="Exclude one or more samples by name. This takes precedence over IMAP membership and `-R`.",
    )
    filtering.add_argument(
        "-R", "--include-reference", action="store_true",
        help="Include `assembly_reference_sequence`. By default it is excluded unless IMAP already contains it.",
    )
    filtering.add_argument(
        "-i", "--imap", metavar="Path", type=Path,
        help="Sample-to-population mapping file with `sample<TAB>population` or `glob<TAB>population` on each line.",
    )
    filtering.add_argument(
        "-g", "--minmap", metavar="Path", type=Path,
        help=(
            "Population-to-minimum-coverage mapping file with "
            "`population<TAB>min` on each line. Adds per-population minimum "
            "coverage checks on top of `-m` when `imap` is used."
        ),
    )

    export = tool.add_argument_group("Linkage and export")
    export.add_argument(
        "--no-subsample", action="store_true",
        help="Keep linked SNPs. By default snpex subsamples one SNP per RAD locus.",
    )
    export.add_argument(
        "--seed", metavar="int", type=int,
        help="Random seed for reproducible one-SNP-per-locus subsampling.",
    )
    export.add_argument(
        "--plink", action="store_true",
        help="Also write PLINK BED/BIM/FAM files for the exported SNP set.",
    )
    export.add_argument(
        "--phylip", action="store_true",
        help="Also write the exported SNP matrix as a PHYLIP alignment.",
    )
    export.add_argument(
        "--nexus", action="store_true",
        help="Also write the exported SNP matrix as a NEXUS alignment.",
    )
    export.add_argument(
        "--fasta", action="store_true",
        help="Also write the exported SNP matrix as a FASTA alignment.",
    )
    export.add_argument(
        "--treemix", action="store_true",
        help="Also write TreeMix population-count input for the exported SNP set.",
    )
    export.add_argument(
        "--eems", action="store_true",
        help="Also write an EEMS genetic-dissimilarity matrix for the exported SNP set.",
    )
    export.add_argument(
        "-I", "--impute-method", metavar="str", choices=("sample", "zero-fill", "zero"),
        help="Optional imputation method applied before writing any outputs. Omit to preserve missing genotypes.",
    )

    performance = tool.add_argument_group("Performance and overwrite")
    performance.add_argument(
        "-c", "--cores", metavar="int", type=int, default=1,
        help="Number of cores to use during chunked SNP filtering. [default=1]",
    )
    performance.add_argument(
        "-f", "--force", action="store_true",
        help="Overwrite existing output files with identical names.",
    )

    logging = tool.add_argument_group("Logging")
    logging.add_argument(
        "-l", "--log-level", metavar="str", type=str, default="INFO",
        help="Log level (TRACE, DEBUG, INFO, WARNING, ERROR) [default=INFO]",
    )
    logging.add_argument(
        "-h", "--help", action="help",
        help="Show this help message and exit.",
    )
