#!/usr/bin/env python

"""Window extracter command line."""

import argparse
from pathlib import Path

from .common import RAW_HELP_FORMATTER


EPILOG = r"""
Examples
--------
$ ipyrad2 analysis wex -d HDF5 --print-scaffold-table
$ ipyrad2 analysis wex -d HDF5 -o OUT/
$ ipyrad2 analysis wex -d HDF5 -o OUT/ -n TEST -m 10 -w Chr1
$ ipyrad2 analysis wex -d HDF5 -o OUT/ -n TEST -m 10 -w Chr1 Chr2 Chr3
$ ipyrad2 analysis wex -d HDF5 -o OUT/ -n TEST -m 10 -w Chr[1-3]
$ ipyrad2 analysis wex -d HDF5 -o OUT/ -w Chr1:1-1000
$ ipyrad2 analysis wex -d HDF5 -o OUT/ -w windows.bed -O fa
$ ipyrad2 analysis wex -d HDF5 -o OUT/ -w windows.bed -i POPs.txt -g MINs.txt
"""


def _setup_wex_subparser(
    subparsers: argparse._SubParsersAction,
    header: str = None,
) -> None:
    """Add `ipyrad2 analysis wex` subcommand parser."""
    tool = subparsers.add_parser(
        "wex",
        description=header,
        help="Extract one alignment from selected genomic windows.",
        epilog=EPILOG,
        formatter_class=RAW_HELP_FORMATTER,
        add_help=False,
    )

    core = tool.add_argument_group("Core inputs")
    core.add_argument(
        "-d", "--data", metavar="Path", type=Path, required=True,
        help="Path to an assembly HDF5 file generated by ipyrad2.",
    )
    core.add_argument(
        "-n", "--name", metavar="str", type=str, default="alignment",
        help="Prefix name for the output alignment and stats files. [default=alignment]",
    )
    core.add_argument(
        "-o", "--out", metavar="Path", type=Path, default="output-wex",
        help="Directory to write alignment and stats files. [default=output-wex]",
    )
    core.add_argument(
        "-O", "--out-format", metavar="str", choices=["phy", "nex", "fa"], default="phy",
        help="Output alignment format: phylip (`phy`), nexus (`nex`), or fasta (`fa`). [default=phy]",
    )

    sampling = tool.add_argument_group("Locus sampling")
    sampling.add_argument(
        "-w", "--windows", metavar="str", type=str, nargs="*",
        help="Optional scaffold names, regexes, `scaff:start-end` regions, or a BED file path. "
        "If omitted, wex selects the full length of all scaffolds. Region strings use 1-based inclusive "
        "coordinates; BED uses standard 0-based half-open coordinates.",
    )

    filtering = tool.add_argument_group("Filtering and samples")
    filtering.add_argument(
        "-m", "--min-sample-coverage", metavar="int", type=int, default=4,
        help="Minimum number of samples that must have data at a site. [default=4]",
    )
    filtering.add_argument(
        "-r", "--max-sample-missing", metavar="float", type=float, default=1.0,
        help="Maximum missing-site frequency allowed before excluding a sample. [default=1.0]",
    )
    filtering.add_argument(
        "-e", "--exclude", metavar="str", type=str, nargs="*",
        help="Exclude one or more samples by name. This takes precedence over IMAP membership and `-R`.",
    )
    filtering.add_argument(
        "-R", "--include-reference", action="store_true",
        help="Include `assembly_reference_sequence`. By default it is excluded unless IMAP already contains it.",
    )
    filtering.add_argument(
        "-i", "--imap", metavar="Path", type=Path,
        help="Sample-to-population mapping file with `sample<TAB>population` or `glob<TAB>population` on each line.",
    )
    filtering.add_argument(
        "-g", "--minmap", metavar="Path", type=Path,
        help="Population-to-minimum-coverage mapping file with `population<TAB>min` on each line. Overrides `-m`.",
    )

    output = tool.add_argument_group("Output control")
    output.add_argument(
        "-P", "--print-scaffold-table", action="store_true",
        help="Print the scaffold table to stdout and exit.",
    )
    output.add_argument(
        "-x", "--stdout", action="store_true",
        help="Write the alignment to stdout instead of a file.",
    )
    output.add_argument(
        "-f", "--force", action="store_true",
        help="Overwrite existing output files with identical names.",
    )

    logging = tool.add_argument_group("Logging")
    logging.add_argument(
        "-l", "--log-level", metavar="str", type=str, default="INFO",
        help="Log level (TRACE, DEBUG, INFO, WARNING, ERROR) [default=INFO]",
    )
    logging.add_argument(
        "-h", "--help", action="help",
        help="Show this help message and exit.",
    )
