#!/usr/bin/env python

"""BPP command line."""

import argparse
from pathlib import Path

from .common import RAW_HELP_FORMATTER


EPILOG = r"""
Examples
--------
$ ipyrad2 bpp -d assembly.hdf5 -o OUT/ -n demo --tree species.nwk -i IMAP.txt -g MINMAP.txt -N 1000 -L 100 --threads 50 --seed 123 --tauprior 3 0.05
$ ipyrad2 bpp -d assembly.hdf5 -o OUT/ -n demo --tree species_msci.nwk -i IMAP.txt -g MINMAP.txt -N 1000 -L 100 --threads 50 --seed 123 --tauprior 3 0.05 --msc-i --phiprior 1 1
$ ipyrad2 bpp -d assembly.hdf5 -o OUT/ -n demo --tree species_mscm.nwk -i IMAP.txt -g MINMAP.txt -N 1000 -L 100 --threads 50 --seed 123 --msc-m 0,1 1,0 2,3 3,2 "(0,1),2" --wprior 2 200
$ ipyrad2 bpp -d assembly.hdf5 -o OUT/ -n demo --tree species.nwk -i IMAP.txt -g MINMAP.txt -N 1000 -L 100 --threads 50 --seed 123 --speciestree --speciesmodelprior 1
$ ipyrad2 bpp -d assembly.hdf5 -o OUT/ -n demo --tree species.nwk -i IMAP.txt -g MINMAP.txt -N 1000 -L 100 --threads 50 --seed 123 --speciesdelimitation --speciesmodelprior 1
"""


def _setup_bpp_subparser(
    subparsers: argparse._SubParsersAction,
    header: str = None,
) -> None:
    """Add `ipyrad2 bpp` subcommand parser."""
    tool = subparsers.add_parser(
        "bpp",
        description=header,
        help="Stage one BPP analysis from sequence HDF5 data and optionally run BPP.",
        epilog=EPILOG,
        formatter_class=RAW_HELP_FORMATTER,
        add_help=False,
    )

    core = tool.add_argument_group("Core inputs")
    core.add_argument(
        "-d", "--data", metavar="Path", type=Path, required=True,
        help="Path to an assembly HDF5 file generated by ipyrad2.",
    )
    core.add_argument(
        "-o", "--out", metavar="Path", type=Path, default="output-bpp",
        help="Directory to write staged BPP files and outputs. [default=output-bpp]",
    )
    core.add_argument(
        "-n", "--name", metavar="str", type=str, default="bpp",
        help="Prefix name for staged and output files. [default=bpp]",
    )
    core.add_argument(
        "--tree", metavar="str|Path", type=str, required=True,
        help="Guide tree as inline Newick text or a path to a tree file.",
    )
    core.add_argument(
        "-i", "--imap", metavar="Path", type=Path, required=True,
        help="Sample-to-population mapping file with `sample<TAB>population` or `glob<TAB>population` on each line.",
    )
    core.add_argument(
        "-g", "--minmap", metavar="Path", type=Path, required=True,
        help="Population-to-minimum-coverage mapping file with `population<TAB>min` on each line.",
    )

    sampling = tool.add_argument_group("Locus sampling")
    sampling.add_argument(
        "-N", "--max-loci", metavar="int", type=int, required=True,
        help="Maximum number of loci to sample for this BPP run.",
    )
    sampling.add_argument(
        "-L", "--min-length", metavar="int", type=int, required=True,
        help="Minimum whole-locus length in bp before and after filtering.",
    )

    model = tool.add_argument_group("Model selection")
    selected_model = model.add_mutually_exclusive_group()
    selected_model.add_argument(
        "--msc-i", action="store_true",
        help="Run BPP algorithm 00 with episodic migration using an extended Newick tree.",
    )
    selected_model.add_argument(
        "--msc-m", metavar="str", nargs="+",
        help="Run BPP algorithm 00 with migration pairs like `A,B` or `(A,B),C`.",
    )
    selected_model.add_argument(
        "--speciestree", action="store_true",
        help="Run BPP algorithm 10 species-tree inference.",
    )
    selected_model.add_argument(
        "--speciesdelimitation", action="store_true",
        help="Run BPP algorithm 01 species delimitation.",
    )

    priors = tool.add_argument_group("Priors")
    priors.add_argument(
        "--thetaprior", metavar=("A", "B"), nargs=2, type=float, default=(3.0, 0.03),
        help="Theta prior as inverse-gamma alpha beta. [default=3 0.03]",
    )
    priors.add_argument(
        "--tauprior", metavar=("A", "B"), nargs=2, type=float, default=(3.0, 0.03),
        help="Root tau prior as inverse-gamma alpha beta. [default=3 0.03]",
    )
    priors.add_argument(
        "--speciesmodelprior", metavar="int", type=int, choices=(0, 1, 2, 3), default=0,
        help="Species model prior code used by BPP. [default=0]",
    )
    priors.add_argument(
        "--phiprior", metavar=("A", "B"), nargs=2, type=float, default=(1.0, 1.0),
        help="MSC-I introgression prior as beta alpha beta. [default=1 1]",
    )
    priors.add_argument(
        "--wprior", metavar=("A", "B"), nargs=2, type=float, default=(2.0, 200.0),
        help="MSC-M migration-rate prior as gamma alpha beta. [default=2 200]",
    )
    priors.add_argument(
        "--alphaprior", metavar=("A", "B", "NCAT"), nargs=3, default=(1.0, 1.0, 4),
        help="Among-site rate prior as gamma alpha beta ncategories. [default=1 1 4]",
    )

    rates = tool.add_argument_group("Rate variation")
    rates.add_argument(
        "--locusrate", metavar="str", nargs="+",
        help="Raw BPP `locusrate` tokens. [default=1 2 3 2 iid]",
    )
    rates.add_argument(
        "--clock", metavar="str", nargs="+",
        help="Raw BPP `clock` tokens. [default=2 10.0 100.0 5.0 dir LN]",
    )

    sampler = tool.add_argument_group("MCMC sampler")
    sampler.add_argument(
        "--burnin", metavar="int", type=int, default=1000,
        help="Iterations skipped at the start and used to finetune the sampler. [default=1000]",
    )
    sampler.add_argument(
        "--samplefreq", metavar="int", type=int, default=2,
        help="Frequency of sampling from the MCMC chain. [default=2]",
    )
    sampler.add_argument(
        "--nsample", metavar="int", type=int, default=10000,
        help="Number of MCMC samples to draw. [default=10000]",
    )

    runtime = tool.add_argument_group("Runtime")
    runtime.add_argument(
        "--threads", metavar="int", nargs="+", type=int,
        help="BPP threads as nthreads [start increment]; nthreads also controls seqex preprocessing.",
    )
    runtime.add_argument(
        "--seed", metavar="none|int", type=str,
        help="Random seed for locus subsampling and the BPP ctl file. Use `none` for BPP auto-seeding.",
    )
    runtime.add_argument(
        "--write-only", action="store_true",
        help="Only write the seqfile, imapfile, and ctl file; do not run the BPP binary.",
    )
    runtime.add_argument(
        "-f", "--force", action="store_true",
        help="Overwrite existing staged files and outputs with identical names.",
    )

    logging = tool.add_argument_group("Logging")
    logging.add_argument(
        "-l", "--log-level", metavar="str", type=str, default="INFO",
        help="Log level (TRACE, DEBUG, INFO, WARNING, ERROR) [default=INFO]",
    )
    logging.add_argument(
        "-h", "--help", action="help",
        help="Show this help message and exit.",
    )
