#!/usr/bin/env python

"""Locus extracter command line."""

import argparse
from pathlib import Path

from .common import RAW_HELP_FORMATTER


EPILOG = r"""
Examples
--------
$ ipyrad2 analysis lex -d assembly.hdf5 -o OUT/ -n TEST -m 10 -N 100 -L 150
$ ipyrad2 analysis lex -d assembly.hdf5 -o OUT/ -w Chr1 Chr2 -N 50 -O nex
$ ipyrad2 analysis lex -d assembly.hdf5 -o OUT/ -w Chr1:1-50000 -N 25 -L 300 -O bpp
"""


def _setup_lex_subparser(
    subparsers: argparse._SubParsersAction,
    header: str = None,
) -> None:
    """Add `ipyrad2 analysis lex` subcommand parser."""
    tool = subparsers.add_parser(
        "lex",
        description=header,
        help="Extract delimited loci from an HDF5 database.",
        epilog=EPILOG,
        formatter_class=RAW_HELP_FORMATTER,
        add_help=False,
    )

    core = tool.add_argument_group("Core inputs")
    core.add_argument(
        "-d", "--data", metavar="Path", type=Path, required=True,
        help="Path to an assembly HDF5 file generated by ipyrad2.",
    )
    core.add_argument(
        "-n", "--name", metavar="str", type=str, default="alignment",
        help="Prefix name for output files. [default=alignment]",
    )
    core.add_argument(
        "-o", "--out", metavar="Path", type=Path, default="output-lex",
        help="Directory to write locus alignments and stats files. [default=output-lex]",
    )
    core.add_argument(
        "-O", "--out-format", metavar="str", choices=["phy", "nex", "bpp"], default="phy",
        help="Output format: phylip (`phy`), nexus (`nex`), or BPP (`bpp`). [default=phy]",
    )

    sampling = tool.add_argument_group("Locus sampling")
    sampling.add_argument(
        "-w", "--windows", metavar="str", type=str, nargs="*",
        help="Optional scaffold names, regexes, or `scaff:start-end` regions to sample loci from.",
    )
    sampling.add_argument(
        "-N", "--max-loci", metavar="int", type=int, default=100,
        help="Number of randomly sampled loci to extract. [default=100]",
    )
    sampling.add_argument(
        "-L", "--min-length", metavar="int", type=int, default=150,
        help="Minimum whole-locus length in bp before and after filtering. [default=150]",
    )

    filtering = tool.add_argument_group("Filtering and samples")
    filtering.add_argument(
        "-m", "--min-sample-coverage", metavar="int", type=int, default=4,
        help="Minimum number of samples that must have data at a site. [default=4]",
    )
    filtering.add_argument(
        "-r", "--max-sample-missing", metavar="float", type=float, default=1.0,
        help="Maximum missing-site frequency allowed before excluding a sample. [default=1.0]",
    )
    filtering.add_argument(
        "-e", "--exclude", metavar="str", type=str, nargs="*",
        help="Exclude one or more samples by name. This takes precedence over IMAP membership and `-R`.",
    )
    filtering.add_argument(
        "-R", "--include-reference", action="store_true",
        help="Include `assembly_reference_sequence`. By default it is excluded unless IMAP already contains it.",
    )
    filtering.add_argument(
        "-i", "--imap", metavar="Path", type=Path,
        help="Sample-to-population mapping file with `sample<TAB>population` on each line.",
    )
    filtering.add_argument(
        "-g", "--minmap", metavar="Path", type=Path,
        help="Population-to-minimum-coverage mapping file with `population<TAB>min` on each line. Overrides `-m`.",
    )

    output = tool.add_argument_group("Output control")
    output.add_argument(
        "-P", "--print-scaffold-table", action="store_true",
        help="Print the scaffold table to stdout and exit.",
    )
    output.add_argument(
        "-x", "--stdout", action="store_true",
        help="Write the alignment to stdout instead of a file.",
    )
    output.add_argument(
        "-f", "--force", action="store_true",
        help="Overwrite existing output files with identical names.",
    )

    logging = tool.add_argument_group("Logging")
    logging.add_argument(
        "-l", "--log-level", metavar="str", type=str, default="INFO",
        help="Log level (TRACE, DEBUG, INFO, WARNING, ERROR) [default=INFO]",
    )
    logging.add_argument(
        "-h", "--help", action="help",
        help="Show this help message and exit.",
    )
