#!/usr/env/bin python

"""Locus extracter command line
"""

import argparse
from pathlib import Path
from .make_wide import make_wide


EPILOG = r"""
Examples
--------
$ ipyrad lex -d seqs.hdf5 -o OUT/ -n TEST -m 10 -N 100 -L 150
"""


def _setup_lex_subparser(subparsers: argparse._SubParsersAction, header: str = None) -> None:
    """Add `ipyrad analysis lex` subcommand parser.

    """
    tool = subparsers.add_parser(
        "lex",
        description=header,
        help="Locus extracter to select and write random alignments.",
        epilog=EPILOG,
        formatter_class=make_wide(argparse.RawDescriptionHelpFormatter, max_help_position=60, width=140),
    )
    tool.add_argument(
        "-d", "--data", metavar="Path", type=Path, required=True,
        help="Path to a seqs.hdf5 file generated by ipyrad2",
    )
    tool.add_argument(
        "-n", "--name", metavar="str", type=str, default="alignment",
        help="Prefix name for output alignment and stats files. [default='alignment']",
    )
    tool.add_argument(
        "-o", "--out", metavar="Path", type=Path, default=".",
        help="Directory to write alignment and stats files. Created if it doesn't exist. [default=.]",
    )
    tool.add_argument(
        "-N", "--nloci", metavar="int", type=int, default=100,
        help="Number of randomly sampled loci to extract.",
    )
    tool.add_argument(
        "-L", "--length", metavar="int", type=int, default=150,
        help="Length of loci to extract (in bp).",
    )
    tool.add_argument(
        "-O", "--out-format", metavar="str", choices=["phy", "nex", "fa"], default="phy",
        help="Output alignment file format (phy, nex, inex, or fa). [default=phy]",
    )
    tool.add_argument(
        "-w", "--windows", metavar="str", type=str, nargs="*",
        help="Select one or more 'scaff' or 'scaff:start-end' (1-indexed) regions to extract an alignment from."
    )
    tool.add_argument(
        "-m", "--min-sample-coverage", metavar="int", type=int, default=4,
        help="Min num samples that must have data at a site. [default=4]",
    )
    tool.add_argument(
        "-r", "--max-sample-missing", metavar="float", type=float, default=1.0,
        help="Max frequency of missing sites before a sample is excluded. [default=1.0]",
    )
    tool.add_argument(
        "-i", "--imap", metavar="Path", type=Path,
        help="Individual-to-population mapping file with sample\tpop on each line. "
        "This subselects only the samples in the file, and allows applying the "
        "'-g' min population coverage filters.",
    )
    tool.add_argument(
        "-g", "--minmap", metavar="Path", type=Path,
        help="Population-to-minimum population sample coverage mapping file with pop\tmin on "
        "each line. The alignment will only include site where every population has sequences "
        "from its assigned minimum number of samples. Overrides '-m'."
    )
    tool.add_argument(
        "-e", "--exclude", metavar="str", type=str, nargs="*",
        help="Exclude one or more samples by name. Simpler than using an imap when "
        "only exluding few samples. Imap overrides this arg."
    )
    tool.add_argument(
        "-P", "--print-scaffold-table", action="store_true",
        help="Print the scaffold table to stdout and exit.",
    )
    tool.add_argument(
        "-x", "--stdout", action="store_true",
        help="Write alignment to stdout instead of a file.",
    )
    tool.add_argument(
        "-f", "--force", action="store_true",
        help="Overwrite existing output files with identical names.",
    )
    tool.add_argument(
        "--log-level", metavar="str", type=str, default="INFO",
        help="Log level (DEBUG, INFO, WARN, ERROR) [default=INFO]",
    )
    tool.add_argument(
        "--log-file", metavar="Path", type=Path,
        help="Log file. Logging to stdout is also appended to this file. [default=None]."
    )
